<a href="https://colab.research.google.com/github/afullhart/climateanalogs/blob/main/Figures/Tables.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
%reset -f

### Imports

In [6]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

### ZeroOne Ecoregion Lvl 3 Accuracy

In [ ]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)


test_groups = ['34', '125671012', '101114', '81315', '912']
diag_group = [['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]


df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_eco3_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
avg_area_norm = 0.0
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['US_L3_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)
  avg_area_norm += area_norm * (area_n / n)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')
#print(f'Average area-norm classification rate: {avg_area_norm*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_125678.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv']

,US_L3_13,US_L3_14,US_L3_18,US_L3_19,US_L3_20,US_L3_21,US_L3_22,US_L3_23,US_L3_24,US_L3_25,US_L3_26,US_L3_5,US_L3_79,US_L3_80,US_L3_81
0,418401,76411,3662,64570,146992,38167,195033,152034,71140,4,11814,1345,53556,60889,124827
255,26645,10,873,1269,1588,1488,3021,3920,29023,45717,89401,53,708,870,7

0.9753135013471411
0.8180269280379048
0.8251285235407819
0.9030606650823746
0.9499254052202795
Average accuracy score: 89.42910046456964
Average true positive rate: 83.86382003889365
Average true negative rate: 91.43628028273247
Area-norm classification rate: 87.65005016081305

### ZeroOne MLRA Accuracy

In [7]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)


test_groups = ['34', '12567812', '101114', '813', '15', '912']
diag_group = [['30', '40'], ['24', '27', '28A', '29', '34A', '34B', '35', '42B'],
                ['11', '13', '22A', '23', '25', '26', '28B', '36', '46', '47', '48A', '51'], ['38', '41'],
                ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]


df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_mlra_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
avg_area_norm = 0.0
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['MLRAR_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)
  avg_area_norm += area_norm * (area_n / n)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')
#print(f'Average area-norm classification rate: {avg_area_norm*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_12567812.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv']

,MLRAR_11,MLRAR_13,MLRAR_22A,MLRAR_23,MLRAR_24,MLRAR_25,MLRAR_26,MLRAR_27,MLRAR_28A,MLRAR_28B,...,MLRAR_46,MLRAR_47,MLRAR_48A,MLRAR_51,MLRAR_70A,MLRAR_70B,MLRAR_77B,MLRAR_77C,MLRAR_77D,MLRAR_77E
0,228,1543,1311,19377,39206,62570,15025,59036,123280,84630,...,2458,73315,40551,1812,1348,649,0,0,0,0
255,37,786,66,147,1186,1618,382,1106,22585,749,...,19,888,1930,25,29930,55782,5817,8661,18505,1083

0.9795316846491022
0.784786095663765
0.8549527052498528
0.91743745980747
0.9430578107175152
0.9547004008781375
Average accuracy score: 90.57443594943071
Average true positive rate: 74.53446519556122
Average true negative rate: 92.25929870995068
Area-norm classification rate: 83.39688195275595

### Zscore Ecoregion Lvl 3 Accuracy

In [ ]:
import numpy as np
import os
import pandas as pd
import matplotlib.pyplot as plt

fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)

test_groups = ['134', '2567812', '91115', '9121314', '10']
diag_group = [['14', '81'], ['13', '18', '20', '22', '24'], ['23', '79'], ['5', '19', '21', '80'], ['25', '26']]

df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_eco3_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['US_L3_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_125678.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_eco3_134.csv', 'Zonal_eco3_2567812.csv', 'Zonal_eco3_91115.csv', 'Zonal_eco3_9121314.csv', 'Zonal_eco3_10.csv', 'Zonal_mlra_13.csv', 'Zonal_mlra_24568.csv', 'Zonal_mlra_7912.csv', 'Zonal_mlra_10.csv', 'Zonal_mlra_11.csv', 'Zonal_mlra_1314.csv']

,US_L3_13,US_L3_14,US_L3_18,US_L3_19,US_L3_20,US_L3_21,US_L3_22,US_L3_23,US_L3_24,US_L3_25,US_L3_26,US_L3_5,US_L3_79,US_L3_80,US_L3_81
0,349970,76336,2270,61174,132988,35981,156995,139485,70987,4,6484,1321,53555,42179,124827
255,95076,85,2265,4665,15592,3674,41059,16469,29176,45717,94731,77,709,19580,7

0.9294183085525902
0.7086165286262857
0.7161733309187046
0.7435818306581464
0.8552935190626313
Average accuracy score: 79.06167035636716
Average true positive rate: 62.01717325119166
Average true negative rate: 83.82380580552118
Area-norm classification rate: 72.92048952835641

### Zscore MLRA Accuracy

In [ ]:

import os
import pandas as pd
import matplotlib.pyplot as plt


fld = '/content/drive/My Drive/Colab Notebooks/Analogs/Binary_Test'

files = [f for f in os.listdir(fld) if f[-4:] == '.csv']
print(files)

test_groups = ['13', '24568', '7912', '10', '11', '1314']
diag_group = [['30', '40'], ['24', '26', '27', '28A', '29', '34B', '35', '42B'],
              ['11', '13', '23', '25', '28B', '34A', '36', '39', '51'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E'],
              ['38', '41'], ['22A', '46', '47', '48A']]

df_dict = {}
for n in test_groups:
  df = pd.read_csv(os.path.join(fld, 'Zonal_mlra_{}.csv'.format(n)))
  mask = df.iloc[:, 1:].any(axis=1)
  df = df.iloc[:, 1:][mask]
  n_classes = len(df)
  df_dict[n] = df

display(df)

true_positive_rate_list = []
true_negative_rate_list = []
area_norm_list = []
test_scores = []
for i, df_key in enumerate(df_dict):
  df = df_dict[df_key]
  n = df.sum().sum()
  sum_values_per_col = df.sum()
  codes = ['MLRAR_' + diag_group[i][j] for j in range(len(diag_group[i]))]
  anti_codes = [c for c in df.columns.to_list() if c not in codes]
  yes_n = float(df[codes].loc[255, :].sum())
  no_n = float(df[codes].loc[0, :].sum())
  anti_yes_n = float(df[anti_codes].loc[255, :].sum())
  anti_no_n = float(df[anti_codes].loc[0, :].sum())
  area_n = yes_n + no_n
  anti_area_n = anti_yes_n + anti_no_n

  true_positive = yes_n
  true_negative = anti_no_n
  false_positive = anti_yes_n
  false_negative =  no_n

  group_accuracy = (true_positive + true_negative) / (true_positive + true_negative + false_positive + false_negative)
  print(group_accuracy)
  test_scores.append(group_accuracy)
  true_positive_rate = yes_n / (yes_n + no_n)
  true_negative_rate = anti_no_n / (anti_no_n + anti_yes_n)
  true_positive_rate_list.append(true_positive_rate)
  true_negative_rate_list.append(true_negative_rate)
  area_norm = (true_positive_rate + true_negative_rate) / 2.0
  area_norm_list.append(area_norm)

print(f'Average accuracy score: {np.average(test_scores)*100}')
print(f'Average true positive rate: {np.average(true_positive_rate_list)*100}')
print(f'Average true negative rate: {np.average(true_negative_rate_list)*100}')
print(f'Area-norm classification rate: {np.average(area_norm_list)*100}')

['Zonal_eco3_125671012.csv', 'Zonal_eco3_34.csv', 'Zonal_eco3_81315.csv', 'Zonal_eco3_912.csv', 'Zonal_eco3_101114.csv', 'Zonal_mlra_125678.csv', 'Zonal_mlra_34.csv', 'Zonal_mlra_813.csv', 'Zonal_mlra_912.csv', 'Zonal_mlra_101114.csv', 'Zonal_mlra_15.csv', 'Zonal_eco3_134.csv', 'Zonal_eco3_2567812.csv', 'Zonal_eco3_91115.csv', 'Zonal_eco3_9121314.csv', 'Zonal_eco3_10.csv', 'Zonal_mlra_13.csv', 'Zonal_mlra_24568.csv', 'Zonal_mlra_7912.csv', 'Zonal_mlra_10.csv', 'Zonal_mlra_11.csv', 'Zonal_mlra_1314.csv']

,MLRAR_11,MLRAR_13,MLRAR_22A,MLRAR_23,MLRAR_24,MLRAR_25,MLRAR_26,MLRAR_27,MLRAR_28A,MLRAR_28B,...,MLRAR_46,MLRAR_47,MLRAR_48A,MLRAR_51,MLRAR_70A,MLRAR_70B,MLRAR_77B,MLRAR_77C,MLRAR_77D,MLRAR_77E
0,247,2102,285,19074,39936,56051,14965,60100,141296,83302,...,1146,27963,28281,1791,30290,55974,5817,8661,18505,1083
255,18,227,1092,450,456,8137,442,42,4569,2077,...,1331,46240,14200,46,988,457,0,0,0,0

0.8924626532859934
0.6706762693447724
0.6758461682505501
0.7843161048541488
0.8170097250522965
0.8889608213689976
Average accuracy score: 78.82119570261264
Average true positive rate: 27.354548017918468
Average true negative rate: 86.95511336374615
Area-norm classification rate: 57.154830690832306

### Print ZeroOne Diagnostic Groups

In [8]:
import matplotlib.colors as mcolors
import pandas as pd

zonalf = '/content/drive/My Drive/Colab Notebooks/Analogs/Zonal/Zonal_tavg.csv'

colors = ['#91FE28', '#F4714F', '#FF611B', '#FBAF1C', '#F8E019', '#CCFE29', '#BDBEBE', '#00FE24', '#18F2FE', '#3AC2FD', '#5E79FD', '#6E12FC', '#E21DFD', '#FF18A9', '#FF2B18']
cmap = mcolors.ListedColormap(colors)

df = pd.read_csv(zonalf)
df.index.name = 'arc_id'
df['tavg'] = df['MEAN']
df['color'] = colors

temp_order_df = df.sort_values(by='tavg', ascending=False)
df = temp_order_df.reset_index()
arc_to_order_key = dict(zip(df['Value'].to_list(), [int(x+1) for x in df.index]))
print(arc_to_order_key)

test_groupsA = ['34', '125671012', '101114', '81315', '912']
diag_groupsA = [['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]
#diag_groupsA = [[14, 81], [13, 20, 22, 24], [5, 18, 19, 80], [21, 23, 79], [25, 26]]
test_groupsB = ['34', '12567812', '101114', '813', '15', '912']
diag_groupsB = [['30', '40'], ['24', '27', '28A', '29', '34A', '34B', '35', '42B'],
                ['11', '13', '22A', '23', '25', '26', '28B', '36', '46', '47', '48A', '51'], ['38', '41'],
                ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]

arc_groupsA = [[3, 4], [1, 2, 5, 6, 7, 10, 12], [10, 11, 14], [8, 13, 15], [9, 10, 12]]
ord_groupsA = []
for g in arc_groupsA:
  g_list = []
  for val in g:
    g_list.append(arc_to_order_key[val])
  ord_groupsA.append(g_list)

print(ord_groupsA)
print(diag_groupsA)

arc_groupsB = [[3, 4], [1, 2, 5, 6, 7, 8, 12], [10, 11, 14], [8, 13], [15], [9, 12]]
ord_groupsB = []
for g in arc_groupsB:
  g_list = []
  for val in g:
    g_list.append(arc_to_order_key[val])
  ord_groupsB.append(g_list)

print(ord_groupsB)
print(diag_groupsB)

{4: 1, 3: 2, 8: 3, 9: 4, 13: 5, 1: 6, 2: 7, 5: 8, 7: 9, 6: 10, 12: 11, 10: 12, 15: 13, 11: 14, 14: 15}
[[2, 1], [6, 7, 8, 10, 9, 12, 11], [12, 14, 15], [3, 5, 13], [4, 12, 11]]
[['14', '81'], ['13', '20', '22', '24'], ['5', '18', '19', '21', '80'], ['23', '79'], ['25', '26']]
[[2, 1], [6, 7, 8, 10, 9, 3, 11], [12, 14, 15], [3, 5], [13], [4, 11]]
[['30', '40'], ['24', '27', '28A', '29', '34A', '34B', '35', '42B'], ['11', '13', '22A', '23', '25', '26', '28B', '36', '46', '47', '48A', '51'], ['38', '41'], ['39'], ['42A', '42C', '70A', '70B', '77B', '77C', '77D', '77E']]

### Print Zscore Diagnostic Groups

### ZO Ecoregion Lvl 4 accuracy

In [ ]:
import pandas as pd

zonalf = '/content/drive/My Drive/Colab Notebooks/Analogs/Zonal/Zonal_eco4.csv'

df = pd.read_csv(zonalf)

columns = df.columns[1:]
out_df = pd.DataFrame(columns=columns, index=df.index)

def lvl_label_split(l):
  l = l.split('_')[2]
  return l

def lvl3_label_split(l):
  l = l.split('_')[2]
  numbers = [c for c in l if c.isdigit()]
  numbers = ''.join(numbers)
  return numbers

lvl_labels = columns.map(lvl_label_split).to_list()
lvl3_labels = columns.map(lvl3_label_split).to_list()
lbl_df = pd.DataFrame(data=[lvl_labels, lvl3_labels], columns=columns)

df = pd.concat([lbl_df, df.iloc[:, 1:]], ignore_index=True)

lvl3_set = list(set(df.iloc[1, 1:].to_list()))
for label3 in lvl3_set:
  label_row = df.loc[1]
  filtered_df = df.loc[:, label_row == label3]
  l4_set = list(set(filtered_df.iloc[0, :].to_list()))
  l3_df = filtered_df.iloc[2:, :]
  l3_n = l3_df.sum().sum()
  for i, col in enumerate(l3_df.columns):
    l4_n = l3_df[col].sum()
    for j, val in enumerate(l3_df[col]):
      cc_n = l3_df.iloc[j, :].sum()
      true_positives = val
      false_negatives = l4_n - val
      true_negatives = l3_n - l4_n - cc_n - val
      false_positives = cc_n - val
      #acc_score = (true_positives + true_negatives) / (true_positives + true_negatives + false_positives + false_negatives)
      true_pos_rate = true_positives / (true_positives + false_negatives)
      true_neg_rate = true_negatives / (true_negatives + false_positives)
      true_rate = true_positives / (false_negatives + false_positives)
      #acc_score = (true_pos_rate + true_neg_rate) / 2.0
      acc_score = true_pos_rate
      #acc_score = true_rate
      out_df.at[j, col] = acc_score


display(out_df)

,US_L4_13a,US_L4_13aa,US_L4_13ac,US_L4_13b,US_L4_13c,US_L4_13d,US_L4_13e,US_L4_13f,US_L4_13g,US_L4_13h,...,US_L4_80l,US_L4_81d,US_L4_81g,US_L4_81i,US_L4_81j,US_L4_81k,US_L4_81l,US_L4_81m,US_L4_81n,US_L4_81o
0,0.024932,0.005417,0.0,0.055873,0.00282,0.0,0.0,0.0,0.068152,0.166785,...,0.003479,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,0.002331,0.088961,0.375,0.091905,0.020722,0.003987,0.0,0.008764,0.027523,0.080814,...,0.057063,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.001966,0.0,...,0.0,0.006458,0.795252,0.837226,0.219861,0.668997,0.288961,0.307622,0.555804,0.584615
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.000655,0.0,...,0.0,0.993542,0.092648,0.162459,0.774281,0.027839,0.456912,0.692378,0.444196,0.413187
4,0.020743,0.041772,0.125,0.295442,0.106431,0.00058,0.0,0.0,0.034731,0.052809,...,0.253305,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,0.006824,0.412423,0.5,0.157029,0.285074,0.057563,0.0,0.004241,0.010157,0.04952,...,0.402923,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,0.657376,0.000482,0.0,0.27449,0.016165,0.0,0.0,0.0,0.360747,0.64127,...,0.069589,0.0,0.1121,0.000209,0.005858,0.0,0.0,0.0,0.0,0.0
7,0.0,0.000482,0.0,0.000181,0.0,0.03005,0.0,0.0,0.000655,0.000533,...,0.0,0.0,0.0,0.0,0.0,0.301128,0.254127,0.0,0.0,0.0
8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,0.005675,0.25015,0.0,0.065238,0.386595,0.203647,0.0,0.036472,0.028506,0.001422,...,0.141962,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.000169,0.152281,0.0,0.000227,0.051188,0.476094,0.569448,0.009047,0.004587,0.000089,...,0.004175,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,0.28195,0.042976,0.0,0.059615,0.118214,0.001051,0.0,0.841674,0.46232,0.006757,...,0.067502,0.0,0.0,0.000105,0.0,0.0,0.0,0.0,0.0,0.002198
12,0.0,0.000361,0.0,0.0,0.000453,0.123283,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.002036,0.0,0.0,0.0,0.0
13,0.0,0.004695,0.0,0.0,0.012338,0.080654,0.427333,0.099802,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,0.0,0.0,0.0,0.0,0.0,0.023091,0.003219,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

### ER4 Table

In [ ]:
out_df = out_df

columns = out_df.columns.to_list()


er3_labels = []
er4_labels = []
for l in columns:
  er4_l = l.split('_')[2]
  numbers = [c for c in er4_l if c.isdigit()]
  er3_l = ''.join(numbers)
  er3_labels.append(er3_l)
  er4_labels.append(er4_l)

label_dict = dict(zip(columns, list(zip(er3_labels, er4_labels))))
print(label_dict)

col_maxs = []
for l in columns:
  col_maxs.append([l, out_df[l].max()])

sorted_list = sorted(col_maxs, key=lambda elem: elem[1], reverse=True)
sorted_columns = [elem[0] for elem in sorted_list]

display(pd.DataFrame(sorted_list))

out_list = []
for l in sorted_columns:
  max_idx = out_df[l].idxmax()
  #print(max_idx)
  #display(out_df.loc[max_idx])
  cc_l = max_idx + 1
  five_values = pd.to_numeric(out_df.loc[max_idx]).nlargest(5).tolist()
  five_labels = pd.to_numeric(out_df.loc[max_idx]).nlargest(5).index.tolist()

  out_list.append(['CC', None])
  out_list.append([cc_l, None])

print(five_values)
print(five_labels)

{'US_L4_13a': ('13', '13a'), 'US_L4_13aa': ('13', '13aa'), 'US_L4_13ac': ('13', '13ac'), 'US_L4_13b': ('13', '13b'), 'US_L4_13c': ('13', '13c'), 'US_L4_13d': ('13', '13d'), 'US_L4_13e': ('13', '13e'), 'US_L4_13f': ('13', '13f'), 'US_L4_13g': ('13', '13g'), 'US_L4_13h': ('13', '13h'), 'US_L4_13i': ('13', '13i'), 'US_L4_13j': ('13', '13j'), 'US_L4_13k': ('13', '13k'), 'US_L4_13l': ('13', '13l'), 'US_L4_13m': ('13', '13m'), 'US_L4_13n': ('13', '13n'), 'US_L4_13o': ('13', '13o'), 'US_L4_13p': ('13', '13p'), 'US_L4_13q': ('13', '13q'), 'US_L4_13r': ('13', '13r'), 'US_L4_13s': ('13', '13s'), 'US_L4_13t': ('13', '13t'), 'US_L4_13u': ('13', '13u'), 'US_L4_13v': ('13', '13v'), 'US_L4_13w': ('13', '13w'), 'US_L4_13x': ('13', '13x'), 'US_L4_13y': ('13', '13y'), 'US_L4_13z': ('13', '13z'), 'US_L4_14a': ('14', '14a'), 'US_L4_14b': ('14', '14b'), 'US_L4_14c': ('14', '14c'), 'US_L4_14d': ('14', '14d'), 'US_L4_14e': ('14', '14e'), 'US_L4_14f': ('14', '14f'), 'US_L4_14g': ('14', '14g'), 'US_L4_14h': ('14', '14h'), 'US_L4_14p': ('14', '14p'), 'US_L4_18a': ('18', '18a'), 'US_L4_18c': ('18', '18c'), 'US_L4_18d': ('18', '18d'), 'US_L4_19a': ('19', '19a'), 'US_L4_19b': ('19', '19b'), 'US_L4_19c': ('19', '19c'), 'US_L4_19d': ('19', '19d'), 'US_L4_19e': ('19', '19e'), 'US_L4_19f': ('19', '19f'), 'US_L4_19g': ('19', '19g'), 'US_L4_20a': ('20', '20a'), 'US_L4_20b': ('20', '20b'), 'US_L4_20c': ('20', '20c'), 'US_L4_20d': ('20', '20d'), 'US_L4_20e': ('20', '20e'), 'US_L4_20f': ('20', '20f'), 'US_L4_20g': ('20', '20g'), 'US_L4_20h': ('20', '20h'), 'US_L4_20i': ('20', '20i'), 'US_L4_21a': ('21', '21a'), 'US_L4_21b': ('21', '21b'), 'US_L4_21c': ('21', '21c'), 'US_L4_21d': ('21', '21d'), 'US_L4_21e': ('21', '21e'), 'US_L4_21f': ('21', '21f'), 'US_L4_21g': ('21', '21g'), 'US_L4_21h': ('21', '21h'), 'US_L4_21j': ('21', '21j'), 'US_L4_22a': ('22', '22a'), 'US_L4_22aa': ('22', '22aa'), 'US_L4_22b': ('22', '22b'), 'US_L4_22d': ('22', '22d'), 'US_L4_22f': ('22', '22f'), 'US_L4_22g': ('22', '22g'), 'US_L4_22h': ('22', '22h'), 'US_L4_22i': ('22', '22i'), 'US_L4_22j': ('22', '22j'), 'US_L4_22k': ('22', '22k'), 'US_L4_22l': ('22', '22l'), 'US_L4_22m': ('22', '22m'), 'US_L4_22n': ('22', '22n'), 'US_L4_22o': ('22', '22o'), 'US_L4_22p': ('22', '22p'), 'US_L4_22q': ('22', '22q'), 'US_L4_22r': ('22', '22r'), 'US_L4_22s': ('22', '22s'), 'US_L4_22t': ('22', '22t'), 'US_L4_22u': ('22', '22u'), 'US_L4_22v': ('22', '22v'), 'US_L4_22w': ('22', '22w'), 'US_L4_22x': ('22', '22x'), 'US_L4_22y': ('22', '22y'), 'US_L4_22z': ('22', '22z'), 'US_L4_23a': ('23', '23a'), 'US_L4_23b': ('23', '23b'), 'US_L4_23c': ('23', '23c'), 'US_L4_23d': ('23', '23d'), 'US_L4_23e': ('23', '23e'), 'US_L4_23f': ('23', '23f'), 'US_L4_23g': ('23', '23g'), 'US_L4_23h': ('23', '23h'), 'US_L4_23i': ('23', '23i'), 'US_L4_23j': ('23', '23j'), 'US_L4_23k': ('23', '23k'), 'US_L4_23l': ('23', '23l'), 'US_L4_24a': ('24', '24a'), 'US_L4_24b': ('24', '24b'), 'US_L4_24c': ('24', '24c'), 'US_L4_24d': ('24', '24d'), 'US_L4_24f': ('24', '24f'), 'US_L4_24g': ('24', '24g'), 'US_L4_24h': ('24', '24h'), 'US_L4_25b': ('25', '25b'), 'US_L4_25c': ('25', '25c'), 'US_L4_25e': ('25', '25e'), 'US_L4_25i': ('25', '25i'), 'US_L4_25j': ('25', '25j'), 'US_L4_25k': ('25', '25k'), 'US_L4_26d': ('26', '26d'), 'US_L4_26f': ('26', '26f'), 'US_L4_26h': ('26', '26h'), 'US_L4_26l': ('26', '26l'), 'US_L4_26m': ('26', '26m'), 'US_L4_26n': ('26', '26n'), 'US_L4_26o': ('26', '26o'), 'US_L4_26p': ('26', '26p'), 'US_L4_26q': ('26', '26q'), 'US_L4_5b': ('5', '5b'), 'US_L4_5c': ('5', '5c'), 'US_L4_5f': ('5', '5f'), 'US_L4_79a': ('79', '79a'), 'US_L4_79b': ('79', '79b'), 'US_L4_79c': ('79', '79c'), 'US_L4_79d': ('79', '79d'), 'US_L4_79e': ('79', '79e'), 'US_L4_80a': ('80', '80a'), 'US_L4_80b': ('80', '80b'), 'US_L4_80c': ('80', '80c'), 'US_L4_80d': ('80', '80d'), 'US_L4_80e': ('80', '80e'), 'US_L4_80g': ('80', '80g'), 'US_L4_80h': ('80', '80h'), 'US_L4_80i': ('80', '80i'), 'US_L4_80j': ('80', '80j'), 'US_L4_80k': ('80', '80k'), 'US_L4_80l': ('80', '80l'), 'US_L4_81d': ('81', '81d'), 'US_L4_81g': ('81', '81g'), 'US_L4_81i': ('81', '81i'), 'US_L4_81j': ('81', '81j'), 'US_L4_81k': ('81', '81k'), 'US_L4_81l': ('81', '81l'), 'US_L4_81m': ('81', '81m'), 'US_L4_81n': ('81', '81n'), 'US_L4_81o': ('81', '81o')}

             0         1
0    US_L4_13o  1.000000
1    US_L4_19a  1.000000
2    US_L4_19b  1.000000
3    US_L4_21a  1.000000
4    US_L4_25b  1.000000
..         ...       ...
147  US_L4_20c  0.324410
148  US_L4_19g  0.296198
149  US_L4_13b  0.295442
150  US_L4_24a  0.293409
151  US_L4_13j  0.281778

[152 rows x 2 columns]

[0.703880960668291, 0.5924608819345661, 0.5342226457043037, 0.5110361575822989, 0.503908882598733]
['US_L4_13v', 'US_L4_22s', 'US_L4_13k', 'US_L4_13p', 'US_L4_13r']